
services:
    app.user_repository:
        class: AppBundle\Repository\UserRepository
        factory: ["@doctrine", getRepository]
        arguments: 
            - AppBundle\Entity\User
            
            
    app.user_service:
        class: AppBundle\Service\UserService
        arguments: ['@doctrine.orm.entity_manager']
        
    logging_pointcut:
        class: AppBundle\PointCut\LoggingPointCut
        tags:
            - { name: jms_aop.pointcut, interceptor: logging_interceptor }        
            
    logging_interceptor:
        class: AppBundle\Interceptor\LoggingInterceptor
        arguments: ['@logger']             

    transactional_pointcut:
        class: AppBundle\PointCut\TransactionalPointCut
        arguments: ['@annotation_reader'] 
        tags:
            - { name: jms_aop.pointcut, interceptor: transactional_interceptor } 
            
    transactional_interceptor:
        class: AppBundle\Interceptor\TransactionalInterceptor
        arguments: ['@doctrine.orm.entity_manager']              
